import {
  mdiBabyBottle,
  mdiBabyBottleOutline,
  mdiBabyFace,
  mdiBabyFaceOutline,
  mdiMotherNurse,
  mdiSpoonSugar,
  mdiCupWater,
  mdiSilverwareForkKnife,
  mdiFood,
  mdiFoodApple,
  mdiBottleTonicPlus,
  mdiPill,
  mdiPillMultiple,
  mdiSyringe,
  mdiThermometer,
  mdiHeartPulse,
  mdiScale,
  mdiRuler,
  mdiEye,
  mdiTooth,
  mdiMedicalBag,
  mdiHospitalBox,
  mdiRun,
  mdiRunFast,
  mdiSwim,
  mdiBike,
  mdiSoccer,
  mdiToyBrick,
  mdiPuzzle,
  mdiPaletteOutline,
  mdiMusicNote,
  mdiBalloon,
  mdiHumanChild,
  mdiBed,
  mdiMoonWaningCrescent,
  mdiSleep,
  mdiBook,
  mdiBookOpenPageVariant,
  mdiSchool,
  mdiPencil,
  mdiAbacus,
  mdiAlphabetLatin,
  mdiStar,
  mdiHeart,
  mdiClockOutline,
  mdiCalendar,
  mdiTrophy,
  mdiNoteText,
  mdiBath,
  mdiHandshake,
  mdiCar,
  mdiDog,
  mdiCat,
  mdiFlower,
  mdiWeatherSunny,
  mdiUmbrella,
  mdiCamera,
  mdiVideo,
  mdiGift,
  mdiEmoticonHappy,
  mdiTimer,
  mdiWater,
  mdiWalk,
  mdiDumbbell,
  mdiYoga,
  mdiLeaf,
  mdiFire,
  mdiSnowflake,
  mdiMedication,
  mdiEarHearing,
  mdiHandHeart,
  mdiAccount,
  mdiAccountGroup,
  mdiHome,
} from '@mdi/js';

export interface MdiIconEntry {
  name: string;
  path: string;
  label: string;
}

export interface MdiIconGroup {
  label: string;
  icons: MdiIconEntry[];
}

export const CUSTOM_ACTIVITY_ICON_GROUPS: MdiIconGroup[] = [
  {
    label: 'Baby & Feeding',
    icons: [
      { name: 'mdiBabyBottle', path: mdiBabyBottle, label: 'Baby Bottle' },
      { name: 'mdiBabyBottleOutline', path: mdiBabyBottleOutline, label: 'Bottle Outline' },
      { name: 'mdiBabyFace', path: mdiBabyFace, label: 'Baby Face' },
      { name: 'mdiBabyFaceOutline', path: mdiBabyFaceOutline, label: 'Baby Face Outline' },
      { name: 'mdiMotherNurse', path: mdiMotherNurse, label: 'Nursing' },
      { name: 'mdiSpoonSugar', path: mdiSpoonSugar, label: 'Spoon' },
      { name: 'mdiCupWater', path: mdiCupWater, label: 'Cup/Water' },
      { name: 'mdiSilverwareForkKnife', path: mdiSilverwareForkKnife, label: 'Fork & Knife' },
      { name: 'mdiFood', path: mdiFood, label: 'Food' },
      { name: 'mdiFoodApple', path: mdiFoodApple, label: 'Apple' },
    ],
  },
  {
    label: 'Health & Medical',
    icons: [
      { name: 'mdiBottleTonicPlus', path: mdiBottleTonicPlus, label: 'Medicine Bottle' },
      { name: 'mdiPill', path: mdiPill, label: 'Pill' },
      { name: 'mdiPillMultiple', path: mdiPillMultiple, label: 'Pills' },
      { name: 'mdiSyringe', path: mdiSyringe, label: 'Syringe' },
      { name: 'mdiThermometer', path: mdiThermometer, label: 'Thermometer' },
      { name: 'mdiHeartPulse', path: mdiHeartPulse, label: 'Heart Rate' },
      { name: 'mdiScale', path: mdiScale, label: 'Scale' },
      { name: 'mdiRuler', path: mdiRuler, label: 'Ruler' },
      { name: 'mdiEye', path: mdiEye, label: 'Eye' },
      { name: 'mdiTooth', path: mdiTooth, label: 'Tooth' },
      { name: 'mdiMedicalBag', path: mdiMedicalBag, label: 'Medical Bag' },
      { name: 'mdiHospitalBox', path: mdiHospitalBox, label: 'First Aid' },
      { name: 'mdiMedication', path: mdiMedication, label: 'Medication' },
      { name: 'mdiEarHearing', path: mdiEarHearing, label: 'Hearing' },
    ],
  },
  {
    label: 'Activity & Play',
    icons: [
      { name: 'mdiRun', path: mdiRun, label: 'Run' },
      { name: 'mdiRunFast', path: mdiRunFast, label: 'Run Fast' },
      { name: 'mdiWalk', path: mdiWalk, label: 'Walk' },
      { name: 'mdiSwim', path: mdiSwim, label: 'Swim' },
      { name: 'mdiBike', path: mdiBike, label: 'Bike' },
      { name: 'mdiSoccer', path: mdiSoccer, label: 'Soccer' },
      { name: 'mdiDumbbell', path: mdiDumbbell, label: 'Dumbbell' },
      { name: 'mdiYoga', path: mdiYoga, label: 'Yoga' },
      { name: 'mdiToyBrick', path: mdiToyBrick, label: 'Blocks' },
      { name: 'mdiPuzzle', path: mdiPuzzle, label: 'Puzzle' },
      { name: 'mdiPaletteOutline', path: mdiPaletteOutline, label: 'Art' },
      { name: 'mdiMusicNote', path: mdiMusicNote, label: 'Music' },
      { name: 'mdiBalloon', path: mdiBalloon, label: 'Balloon' },
      { name: 'mdiHumanChild', path: mdiHumanChild, label: 'Child' },
    ],
  },
  {
    label: 'Sleep & Rest',
    icons: [
      { name: 'mdiBed', path: mdiBed, label: 'Bed' },
      { name: 'mdiMoonWaningCrescent', path: mdiMoonWaningCrescent, label: 'Moon' },
      { name: 'mdiSleep', path: mdiSleep, label: 'Sleep' },
    ],
  },
  {
    label: 'Learning',
    icons: [
      { name: 'mdiBook', path: mdiBook, label: 'Book' },
      { name: 'mdiBookOpenPageVariant', path: mdiBookOpenPageVariant, label: 'Open Book' },
      { name: 'mdiSchool', path: mdiSchool, label: 'School' },
      { name: 'mdiPencil', path: mdiPencil, label: 'Pencil' },
      { name: 'mdiAbacus', path: mdiAbacus, label: 'Abacus' },
      { name: 'mdiAlphabetLatin', path: mdiAlphabetLatin, label: 'Alphabet' },
    ],
  },
  {
    label: 'Everyday',
    icons: [
      { name: 'mdiBath', path: mdiBath, label: 'Bath' },
      { name: 'mdiCar', path: mdiCar, label: 'Car' },
      { name: 'mdiHome', path: mdiHome, label: 'Home' },
      { name: 'mdiHandshake', path: mdiHandshake, label: 'Handshake' },
      { name: 'mdiDog', path: mdiDog, label: 'Dog' },
      { name: 'mdiCat', path: mdiCat, label: 'Cat' },
      { name: 'mdiFlower', path: mdiFlower, label: 'Flower' },
      { name: 'mdiWeatherSunny', path: mdiWeatherSunny, label: 'Sunny' },
      { name: 'mdiUmbrella', path: mdiUmbrella, label: 'Umbrella' },
      { name: 'mdiLeaf', path: mdiLeaf, label: 'Leaf' },
      { name: 'mdiFire', path: mdiFire, label: 'Fire' },
      { name: 'mdiSnowflake', path: mdiSnowflake, label: 'Snow' },
      { name: 'mdiWater', path: mdiWater, label: 'Water' },
    ],
  },
  {
    label: 'General',
    icons: [
      { name: 'mdiStar', path: mdiStar, label: 'Star' },
      { name: 'mdiHeart', path: mdiHeart, label: 'Heart' },
      { name: 'mdiClockOutline', path: mdiClockOutline, label: 'Clock' },
      { name: 'mdiCalendar', path: mdiCalendar, label: 'Calendar' },
      { name: 'mdiTrophy', path: mdiTrophy, label: 'Trophy' },
      { name: 'mdiNoteText', path: mdiNoteText, label: 'Note' },
      { name: 'mdiTimer', path: mdiTimer, label: 'Timer' },
      { name: 'mdiCamera', path: mdiCamera, label: 'Camera' },
      { name: 'mdiVideo', path: mdiVideo, label: 'Video' },
      { name: 'mdiGift', path: mdiGift, label: 'Gift' },
      { name: 'mdiEmoticonHappy', path: mdiEmoticonHappy, label: 'Happy' },
      { name: 'mdiHandHeart', path: mdiHandHeart, label: 'Hand Heart' },
      { name: 'mdiAccount', path: mdiAccount, label: 'Person' },
      { name: 'mdiAccountGroup', path: mdiAccountGroup, label: 'Group' },
    ],
  },
];

export const ALL_CUSTOM_ACTIVITY_ICONS: MdiIconEntry[] = CUSTOM_ACTIVITY_ICON_GROUPS.flatMap(
  (g) => g.icons
);

// Lookup map: MDI name → SVG path
export const ICON_PATH_MAP: Record<string, string> = Object.fromEntries(
  ALL_CUSTOM_ACTIVITY_ICONS.map((i) => [i.name, i.path])
);
